CREATE TABLE IF NOT EXISTS Car(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	brand VARCHAR(40) NOT NULL,
	model VARCHAR(40) NOT NULL, 
	created_at TIMESTAMP DEFAULT 0,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);