CREATE TABLE IF NOT EXISTS User_Car (
	user_id INT(11) UNSIGNED NOT NULL,
	car_id INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY(user_id, car_id),
	created_at TIMESTAMP DEFAULT 0,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY(user_id) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(car_id) REFERENCES Car(id) ON DELETE CASCADE ON UPDATE CASCADE
);